version: '3.7'
services:
    jenkins:
        image: jenkins/jenkins
        user: root
        volumes:
            - /usr/bin/docker:/usr/bin/docker:ro
            - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins_home:/var/jenkins_home
        ports:
            - 8080:8080
volumes:
    jenkins_home: